# Config
# ========================================================================================

# Uncomment and set the URL of your site (with protocol, e.g. `https://`)
# NOTE: You don't need to provide this property when hosting on GitHub Pages or Netlify.
 url:                   https://choiyeonhee1.github.io/cyh.github.io/

# Uncomment and set the "base URL" of your site.
# When your site is in a subdirectory, set to `/<name of directory>`,
# with a leading `/` but no trailing `/`. Use the empty string '' otherwise.
# NOTE: You don't need to provide this property when hosting on GitHub Pages or Netlify.
# baseurl:               '/hydejack-starter-kit'


# General settings
# ---------------------------------------------------------------------------------------

lang:                  ko-KR
title:                 블로그 이
description:           >
  Hydejack is a boutique Jekyll theme for hackers, nerds, and academics,
  with a focus on personal sites that are meant to impress.

tagline:               서브 타이틀
keywords:              []
logo:                  /assets/img/logo.png

author:
  name:                <firstname> <lastname>
  email:               <mail@domain.tld>

menu:
  - title:             Example
    url:               /example/
  - title:             Documentation
    url:               /docs/
  - title:             About
    url:               /about/

legal:
  - title:             LICENSE
    url:               /LICENSE/
  - title:             NOTICE
    url:               /NOTICE/
  - title:             CHANGELOG
    url:               /CHANGELOG/

copyright:             © 2024. All rights reserved.
permalink:             /:categories/:year-:month-:day-:title/
paginate:              10
paginate_path:         /:num/


# Theme
# ---------------------------------------------------------------------------------------

remote_theme: hydecorp/hydejack@v9

# Customization
# ----------------------------------------------------------------------------------------

accent_image:          /assets/img/sidebar-bg.jpg
accent_color:          rgb(79,177,186)
theme_color:           rgb(25,55,71)

defaults:
  - scope:
      path:            hyde/
    values:
      accent_color:    rgb(38,139,210)
      theme_color:     rgb(32,32,32)
      accent_image:
        background:    rgb(32,32,32)
        overlay:       false
  - scope:
      path:            assets/
    values:
      sitemap:         false
  - scope:
      path:            licenses/
    values:
      layout:          plain
      sitemap:         false
  - scope:
      type:            projects
    values:
      seo:
        type:          WebPage
  - scope:
      type:            featured_categories
    values:
      seo:
        type:          WebPage
  - scope:
      type:            featured_tags
    values:
      seo:
        type:          WebPage

kramdown:
  math_engine:         katex
  math_engine_opts:    {}
  footnote_backlink:   '&#x21a9;&#xfe0e;'

plugins:
  - jekyll-default-layout
  - jekyll-feed
  - jekyll-optional-front-matter
  - jekyll-paginate
  - jekyll-readme-index
  - jekyll-redirect-from
  - jekyll-relative-links
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-titles-from-headings
  - jekyll-include-cache
  - jekyll-last-modified-at
