# Site settings
title:                cyh Blog
description:          개발 공부중,,
lang:                 ko
tagline:              ""
keywords:             []

# GitHub Pages settings
url:                  "https://choiyeonhee1.github.io"
baseurl:              ""

# Remote theme
remote_theme: hydecorp/hydejack@v9

# Sidebar settings
#logo:                 /assets/img/logo.png
accent_image:         /assets/img/sidebar-bg.jpg
accent_color:         rgb(79,177,186)
theme_color:          rgb(25,55,71)

# Navigation menu
menu:
  - title:            Home
    url:              /
  - title:            Example
    url:              /example/
  - title:            Documentation
    url:              /docs/
  - title:            About
    url:              /about/


# Footer links
#legal:
  #- title:            LICENSE
  #  url:              /LICENSE/
  #- title:            NOTICE
  #  url:              /NOTICE/
  #- title:            CHANGELOG
  #  url:              /CHANGELOG/

# Permalinks
permalink:            /:categories/:year-:month-:day-:title/
paginate:             10
paginate_path:        /page:num/

# Hydejack settings
hydejack:
  post_addons:        [about, newsletter, related, random, comments]
  project_addons:     [about, newsletter, other, comments]
  no_search:          false
  no_toc:             false
  no_large_headings:  false
  dark_mode:
    always:           false
    dynamic:          true
    icon:             true

# Collections
collections:
  projects:
    permalink:        /projects/:path/
    output:           true

# Plugins
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-include-cache

# SEO & Social
webmaster_verifications:
  google:             "<your-google-verification-code>"
