title: "CYH Blog"
description: "개발 공부중,,"
logo_img: "/assets/img/favicon.webp"
profile_img: "/assets/img/Chiikawa_usagi.jpg"

# Social Links
github_username: github


# External API
giscus_repo: "choiyeonhee1/choiyeonhee1.github.io"
giscus_repoId: "R_kgDOOFi4fw"
giscus_category: "Q&A"
giscus_categoryId: "DIC_kwDOOFi4f84CoKTO"
goatcounter_code: byanko77 #방문자 트래픽 추적용 고유코드
google_analytics:


# If your repo name follows the format "<user-name>.github.io", then leave the below blank.
# Otherwise, set its value as "/<repo-name>". ex) baseurl: /myblog
url : https://choiyeonhee1.github.io/
baseurl: ""

# Build settings
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  #- jekyll-loading-lazy
  - jekyll-livereload

exclude:
  - docs/

collections:
  pages:
    output: true
    permalink: /:path.html

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      date: "1900-01-01"

# Markdown newline activator 
kramdown:
  input: GFM
  hard_wrap: true
